export const ELLIPSE_CONTOUR_SEGMENTS = 24;
export const PEN_MAX_CONTOUR_SEGMENTS = 256;
export const PEN_BASE_CONTOUR_SEGMENTS = 256;
export const PEN_ADAPTIVE_STEP_POINTS = 2;
export const PEN_MAX_ADAPTIVE_CONTOUR_SEGMENTS = 4096;
export const CONTOUR_CACHE_MAX_SIZE = 512;
