import { SmartAssistConfig } from "./types";

export const SMART_ASSIST_CONFIG: SmartAssistConfig = {
  enabledByDefault: false,
  shapeDebounceMs: 1100,
  maxBatchStrokes: 6,
  maxBatchAgeMs: 5000,
  maxRawPoints: 1800,
  batchJoinPaddingPx: 160,
  transitionDurationMs: 180,
  text: {
    idleDebounceMs: 1900,
    maxBatchStrokes: 64,
    maxBatchAgeMs: 30000,
    maxRawPoints: 10000,
    joinPaddingPx: 190,
    earlyIntentMinStrokes: 3,
    earlyIntentThreshold: 0.52,
    intentThreshold: 0.56,
    singleStrokeIntentThreshold: 0.48,
    recognitionTimeoutMs: 7000,
    vision: {
      recognitionLevel: "accurate",
      usesLanguageCorrection: true,
      recognitionLanguages: [],
      minimumTextHeight: null,
    },
  },
  minConfidence: {
    line: 0.84,
    arrow: 0.82,
    rectangle: 0.8,
    diamond: 0.84,
    ellipse: 0.61,
  },
  conflictMarginsPx: {
    overlap: 12,
    endpoint: 16,
    axis: 10,
  },
  snap: {
    distancePx: 18,
    axisDistancePx: 18,
    angleIntent: {
      axisMaxAngleDeltaDeg: 12,
      diagonalMaxAngleDeltaDeg: 5,
      axisMaxEndpointShiftRatio: 0.18,
      diagonalMaxEndpointShiftRatio: 0.1,
      axisMinEndpointShiftPx: 20,
      diagonalMinEndpointShiftPx: 14,
      axisMaxEndpointShiftPx: 48,
      diagonalMaxEndpointShiftPx: 30,
    },
  },
};
