// Keep this list small: Vision custom words bias recognition, so broad common
// words can create false positives without helping much.
const SMART_ASSIST_TECHNICAL_WORD_BASE = [
  "ACID",
  "API",
  "APIs",
  "AWS",
  "Azure",
  "BFF",
  "BGP",
  "BigQuery",
  "CDN",
  "CIDR",
  "CLI",
  "CORS",
  "CQRS",
  "CRUD",
  "DNS",
  "DynamoDB",
  "EC2",
  "EKS",
  "ETL",
  "GCP",
  "GraphQL",
  "HTTP",
  "HTTP/2",
  "HTTP/3",
  "HTTPS",
  "IAM",
  "IOPS",
  "JSON",
  "JWT",
  "Kafka",
  "Kinesis",
  "Kubernetes",
  "Lambda",
  "MongoDB",
  "MySQL",
  "NAT",
  "Node.js",
  "NoSQL",
  "OAuth",
  "OIDC",
  "OLAP",
  "OLTP",
  "OpenTelemetry",
  "Postgres",
  "PostgreSQL",
  "PubSub",
  "RDBMS",
  "REST",
  "RPC",
  "RPS",
  "React",
  "Redis",
  "S3",
  "SAML",
  "SDK",
  "SLA",
  "SLO",
  "SNS",
  "SQS",
  "SSE",
  "SQL",
  "SSTable",
  "TCP",
  "TLS",
  "TTL",
  "UDP",
  "URI",
  "URL",
  "UUID",
  "VPC",
  "VPN",
  "WebRTC",
  "WebSocket",
  "YAML",
  "ZooKeeper",
  "gRPC",
  "mTLS",
  "microfrontend",
  "microfrontends",
  "microservice",
  "microservices",
  "protobuf",
  "p50",
  "p90",
  "p95",
  "p99",
] as const;

const lowercaseVariants = SMART_ASSIST_TECHNICAL_WORD_BASE
  .map((word) => word.toLowerCase())
  .filter((word, index) => word !== SMART_ASSIST_TECHNICAL_WORD_BASE[index]);

export const SMART_ASSIST_TECHNICAL_WORDS = Array.from(
  new Set([...SMART_ASSIST_TECHNICAL_WORD_BASE, ...lowercaseVariants])
) as readonly string[];
